{{- range $key, $svc := .Values.services }}
{{- if and $svc.enabled $svc.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $svc.name }}
  labels:
    {{- include "procureflow.labels" $ | nindent 4 }}
spec:
  minAvailable: {{ $svc.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $svc.name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
{{- end }}
