{{- range $key, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $svc.name }}
  labels:
    {{- include "procureflow.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $svc.name }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
