services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root-dev-password
      MYSQL_DATABASE: legacy_procureflow
      MYSQL_USER: procureflow
      MYSQL_PASSWORD: procureflow-dev-password
    ports:
      - "3306:3306"
    volumes:
      - legacy_mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot-dev-password"]
      interval: 10s
      timeout: 5s
      retries: 20

  rabbitmq:
    profiles: ["messaging"]
    image: rabbitmq:3.13-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: procureflow
      RABBITMQ_DEFAULT_PASS: procureflow-dev-password
    ports: ["5672:5672", "15672:15672"]
    volumes: ["rabbitmq_data:/var/lib/rabbitmq"]

  kafka:
    profiles: ["messaging"]
    image: bitnami/kafka:3.7.1
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports: ["9092:9092"]
    volumes: ["kafka_data:/bitnami/kafka"]

  elasticsearch:
    profiles: ["search"]
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports: ["9200:9200"]
    volumes: ["elasticsearch_data:/usr/share/elasticsearch/data"]

volumes:
  legacy_mysql:
  rabbitmq_data:
  kafka_data:
  elasticsearch_data:
