import express from 'express';
import client from 'prom-client';
const app = express();
const port = Number(process.env.PORT || 8080);
app.use(express.json());
client.collectDefaultMetrics({ prefix: 'procureflow_notification_' });
const processed = new client.Counter({ name: 'procureflow_notifications_processed_total', help: 'Simulated notifications processed' });
app.get('/api/notifications/health', (_req, res) => res.json({ status: 'UP', service: 'notification-worker' }));
app.get('/api/notifications', (_req, res) => res.json({ mode: 'simulation', queue: process.env.RABBITMQ_URL || 'not-configured' }));
app.post('/api/notifications', (req, res) => { processed.inc(); res.status(202).json({ status: 'QUEUED_SIMULATION', payload: req.body }); });
app.get('/metrics', async (_req, res) => { res.type(client.register.contentType); res.send(await client.register.metrics()); });
app.listen(port, '0.0.0.0', () => console.log(`notification-worker listening on ${port}`));
