grafana:
  adminPassword: admin-dev-password
  service:
    type: ClusterIP
prometheus:
  prometheusSpec:
    retention: 2d
    resources:
      requests: {cpu: 100m, memory: 512Mi}
      limits: {cpu: 750m, memory: 1Gi}
alertmanager:
  alertmanagerSpec:
    resources:
      requests: {cpu: 50m, memory: 128Mi}
      limits: {cpu: 250m, memory: 256Mi}
