deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
singleBinary:
  replicas: 1
  persistence:
    enabled: true
    size: 1Gi
read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0
